name: Publish Package

on:
  push:
    paths:
      - "**.mod"
    # branches:
    #   - main
  pull_request:
    paths:
      - "**.mod"

env:
  KPM_REG: "docker.io"
  KPM_REPO: "kcllang"

jobs:
  publish_pkg:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git history" above.

    runs-on: ubuntu-latest
    name: Update Package Info on AH 
    steps:

      - name: Install kcl
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
             **.mod
             

      - name: Set up Go
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # - name: Login
      #   if: steps.changed-files.outputs.any_changed == 'true'
      #   run: kcl registry login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Publish to docker.io
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
            #./scripts/push_pkg_from.sh $file
          done

      - name: Publish to ghcr.io
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          #kcl registry login -u ${{ secrets.DEPLOY_ACCESS_NAME }} -p ${{ secrets.DEPLOY_ACCESS_TOKEN }} ghcr.io
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do 
            echo $file
            #./scripts/push_pkg_from.sh $file
          done
        env:
          KPM_REG: "ghcr.io"
          KPM_REPO: "kcl-lang"

      - name: Update artifacthub-pkg.yaml
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            go run main.go $file
          done

      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          git add .
          git commit -m "chore: update artifacthub-pkg.yaml"
          git push
